apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-keycloak
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-keycloak
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: keycloak
          image: jboss/keycloak:6.0.1
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: h2
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-postgresql
  namespace: default
spec:
  selector:
    app: gateway-postgresql
  ports:
    - port: 5432
