#!/usr/bin/env groovy

node {

    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        dir('sentway') {
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }

    }

    stage('install tools') {
         dir('sentway') {
            sh "./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-npm -DnodeVersion=v10.16.0 -DnpmVersion=6.9.0"
         }
    }

    stage('npm install') {
        dir('sentway') {
            sh "./mvnw com.github.eirslett:frontend-maven-plugin:npm"
        }
    }

    stage('backend tests') {
        dir('sentway') {
            try {
                sh "./mvnw verify"
            } catch(err) {
                throw err
            } finally {
                junit '**/target/test-results/**/TEST-*.xml'
            }
        }
    }

    stage('frontend tests') {
        dir('sentway') {
            try {
                sh "./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run test'"
            } catch(err) {
                throw err
            } finally {
                junit '**/target/test-results/TESTS-*.xml'
            }
        }
    }

    stage('packaging') {
        dir('sentway') {
            sh "./mvnw verify -Pprod -DskipTests"
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
    }

    def dockerImage
    stage('publish docker') {
        dir('sentway') {
            // A pre-requisite to this step is to setup authentication to the docker registry
            // https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#authentication-methods
            sh "./mvnw jib:build"
        }
    }
}
