apiVersion: v1
kind: Service
metadata:
  name: sentway
  namespace: sententia
  labels:
    app: sentway
spec:
  selector:
    app: sentway
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
